//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Archiver.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Archiver.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to defaultItemImage.png.
        /// </summary>
        internal static string addItemDefaultImage {
            get {
                return ResourceManager.GetString("addItemDefaultImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://192.168.0.28:5152.
        /// </summary>
        internal static string APIBaseUrl {
            get {
                return ResourceManager.GetString("APIBaseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Album/newAlbum.
        /// </summary>
        internal static string CreateAlbum {
            get {
                return ResourceManager.GetString("CreateAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Item/newItem.
        /// </summary>
        internal static string CreateItem {
            get {
                return ResourceManager.GetString("CreateItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Album/delete.
        /// </summary>
        internal static string DeleteAlbum {
            get {
                return ResourceManager.GetString("DeleteAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Item/delete.
        /// </summary>
        internal static string DeleteItem {
            get {
                return ResourceManager.GetString("DeleteItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Album/get.
        /// </summary>
        internal static string GetAlbumById {
            get {
                return ResourceManager.GetString("GetAlbumById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Item/getAll.
        /// </summary>
        internal static string GetAllAlbumItems {
            get {
                return ResourceManager.GetString("GetAllAlbumItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Album/getAll.
        /// </summary>
        internal static string GetAllAlbums {
            get {
                return ResourceManager.GetString("GetAllAlbums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Item/getAll.
        /// </summary>
        internal static string GetAllItems {
            get {
                return ResourceManager.GetString("GetAllItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Item/get.
        /// </summary>
        internal static string GetItemById {
            get {
                return ResourceManager.GetString("GetItemById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.flaticon.com/free-icons/add - Add icons created by dmitri13 - Flaticon
        ///https://www.flaticon.com/free-icons/picture Picture icons created by Freepik - Flaticon
        ///https://www.flaticon.com/free-icons/camera Camera icons created by Freepik - Flaticon
        ///https://www.flaticon.com/free-icons/info Info icons created by Plastic Donut -Flaticon
        ///https://www.flaticon.com/free-icons/album lbum icons created by Nikita Golubev - Flaticon
        ///https://www.flaticon.com/free-icons/question-mark - Question mark icons c [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string references {
            get {
                return ResourceManager.GetString("references", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Album/update.
        /// </summary>
        internal static string UpdateAlbum {
            get {
                return ResourceManager.GetString("UpdateAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Item/update.
        /// </summary>
        internal static string UpdateItem {
            get {
                return ResourceManager.GetString("UpdateItem", resourceCulture);
            }
        }
    }
}
